name: Add Comment to post page

on:
  issue_comment:
    types:
      - created

jobs:
  generate-post:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run the script
        run: python scripts/issue_comment.py add ${{ github.event.issue.number }} "${{ github.event.comment.user.login }}" "${{ github.event.comment.body }}"

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Add comment to issue #${{ github.event.issue.number }}"
          git push