name: Remove Post HTML

on:
  issues:
    types:
      - deleted

jobs:
  generate-post:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
        
      - name: Install Dependencies
        run: pip install -r requirements.txt  # If you have any dependencies

      - name: Remove Post HTML
        run:  rm posts/${{ github.event.issue.number }}.html

      - name: Remove from recents
        run: python scripts/remove_from_recent.py ${{ github.event.issue.number }}

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Remove HTML of Deleted issue #${{ github.event.issue.number }}"
          git push