name: Generate Post HTML

on:
  issues:
    types:
      - opened  # Trigger on new issue creation

jobs:
  generate-post:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      # - name: Install Dependencies
      #   run: pip install -r requirements.txt  # If you have any dependencies

      - name: Generate Post HTML
        run: python generate_post.py ${{ github.event.issue.number }} "${{ github.event.issue.title }}" "${{ github.event.issue.user.login }}" "${{ github.event.issue.body }}"

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Generate HTML for issue #${{ github.event.issue.number }}"
          git push --set-upstream origin ${{ github.ref }}
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
